---
title: "KNN classification"
author: "Frida Gomam"
date: 2021-03-05

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Handwritten Digit Data

Fit the model


```{r cars}
 library(ElemStatLearn)
mydata = zip.train[sample(1:nrow(zip.train), size = 500), ]
kgrid = c(1:20)
  TrainingError = rep(NA, 20)
  TestError = rep(NA, 20)
for (i in 1:20)
{
TrainingError[i] = mean(FNN::knn(train = mydata[, -1], test = mydata[, -1],
cl = as.factor(mydata[, 1]), k = kgrid[i]) != mydata[, 1])
TestError[i] = mean(FNN::knn(train = mydata[, -1], test = zip.test[, -1],
cl = as.factor(mydata[, 1]), k = kgrid[i]) != zip.test[, 1])
}
```

# Including Plots

Comparing training error to test error. See Figure \@ref(fig:pie) below:

```{r pie, fig.cap='Errors against K value', tidy=FALSE}
plot(kgrid, TestError, ylim = c(0, max(TestError)), ylab = "Test error", 
     xlab = "K value", pch = 16, col = "6")
points(kgrid, TrainingError, pch = 19, col = "4")
legend("bottom", c("Training error", "Test error"), col = c("4", "6"), 
       pch = 19, cex = 1.5, bg='lightblue')

```


